"""adds foreignkey to review

Revision ID: 8abbbc7d5fc4
Revises: 1c0c2007a1d3
Create Date: 2024-10-02 15:32:01.009680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abbbc7d5fc4'
down_revision = '1c0c2007a1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))  # Change to employee_id
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])  # Change to employee_id
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')  # Change to employee_id
    op.drop_column('reviews', 'employee_id')  # Change to employee_id
    # ### end Alembic commands ###
